### ISSUE TITLE
(feat): Automated command syntax

### ISSUE THREAD

**Issue by geowa4** [geowa4/servicelogger#12]
Often we need to send a service log in a script or need to send the same service log to many clusters. To aid in this, the `send` command should have the capability to accept multiple cluster IDs for which to send a service log.

Current workflow:
```
servicelogger search | servicelogger send
```

Proposed workflow:
```
servicelogger search | servicelogger send --cluster-ids=a,b,c,d
```

In the event of a failure to send a servicelog to a specific cluster, that cluster ID (and any other failed cluster IDs) should be printed out to the terminal.

**Comment by geowa4** [comment]
I have marked the title with "wip". I had thoughts about how to automate the usage of this utility for common scripting use cases.

Whether wip or not, thoughts on how this could work are welcome.

**Comment by geowa4** [comment]
Old description: 

Often we need to send a service log in a script or need to send the same service log to many clusters. To aid in these use cases, create a YAML syntax to specify a service log to send and to which clusters. 

Proposed format examples:
```yaml
---
version: v1
service_log:
  url: https://raw.githubusercontent.com/.../log.json
clusters:
  - ...internal_cluster_id...

---
version: v1
service_log:
  source_path: v4/osd/log.json
  parameters:
    NAMESPACE: openshift-etcd
    POD: etcd-0
clusters:
  - ...internal_cluster_id...
```

Note that the YAML may contain multiple documents. 

To avoid duplication in case of failure, this command must produce status output associated with each YAML document. 

TODO
